### PR TITLE
Updated README nd schematics

### PR DESCRIPTION
**Pull request by apdlv72**
I added documentation regarding the difference between UART mode and I2S mode.
I updated schematics to include also DC-DC buck converter and DC jack.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
just a git/github comment: I see that you made the changes on your main branch and then send a pull request. Next time, I suggest that you make a development branch for the new feature like `git checkout -b newfeature` and make the changes on that. In case I don't accept the changes, or only partially, that allows you to keep your main clean and synched with mine.

**Comment by robertoostenveld** [comment]
hmm, I see that there is a problem. Your `main` is  [10 commits ahead](https://github.com/apdlv72/esp8266_artnet_dmx512/compare/robertoostenveld:esp8266_artnet_dmx512:main...main), [12 commits behind](https://github.com/apdlv72/esp8266_artnet_dmx512/compare/main...robertoostenveld:esp8266_artnet_dmx512:main) robertoostenveld:main. 

I cannot merge your new changes, as that would undo some of the changes that I have already made. Can you please merge all my changes first?

**Comment by robertoostenveld** [comment]
Btw, I could manually copy your README and new png image, but that would make your version further out of sync with mine. Hence I propose that you first try to update your version.

**Comment by apdlv72** [comment]
Hi. Please advise how I can sync my version with yours. Actually, when
copying your files to my repo, this was exactly my intention. I assumed
only the recent changes in readme and schematic PNG would be included in
the pull request.

**Comment by robertoostenveld** [comment]
I recommend that you set up https://github.com/robertoostenveld/esp8266_artnet_dmx512.git as a remote, and per convention I recommend you call it `upstream`. You will already have your own https://github.com/apdlv72/esp8266_artnet_dmx512.git as a remote, and I expect that to be called `origin`.

See https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes or https://www.atlassian.com/git/tutorials/syncing or any of the many other tutorials on this. On https://www.fieldtriptoolbox.org/development/git/ you can find the tutorial that we wrote for my large work project (a neuroscience data analysis toolbox), the concepts explained there also apply here, except that you should replace `fieldtrip/fieldtrip` by `robertoostenveld/esp8266_artnet_dmx512`. 

Once you have two remotes, you can pull from "upstream" (mine) to keep up to date, and push all your local changes to  "origin" (yours) on github. Then once your changes are on github, you can send me a pull request and I can review and merge. 

In the future, whenever you plan to work on it, I recommend you always first pull my latest changes from "upstream" (i.e. my "official" version) so that yours does not diverge from mine. And as I already said, please do make changes on a separate feature branch.

Now... in this specific case I can imagine that your repository is already kind of messed up. This has also happened to me too many times. The simplest way to clean up that mess is to copy  your README and image out of the repository (for example on your desktop), and that you then "revert" your last 10 commits or so on your `main` until it is aligned with my repository again. Then you push your local cleaned-up version to github (probably needs a `--force` option) and pull the latest changes from mine to make your `main` branch up to date again. Then you make a new feature branch, copy the README and image back in, commit those, and push _that_ branch to github.

I hope this is more or less clear.

**Comment by robertoostenveld** [comment]
never mind my last comment on cleaning up the mess, it appears that you have already managed fine with #5.

**Pull request closed without merging**
